import React from "react";
import PixelArt from "./PixelArt";

// 16x16 pixel badges, one per campaign stop (route order): the eight Kanto gym
// badges, then a Pokéball for Indigo Plateau and a crown for the final stage.
// K is always the outline, so locked silhouettes keep a readable edge.
export const BADGES = [
	{
		name: "Boulder",
		pal: { K: "#2f3a36", L: "#c4dccf", G: "#8fb3a3", D: "#5f7f72", T: "#a9c9bb", W: "#eef7f2" },
		map: [
			"....KKKKKKKK....",
			"...KLLLLLLLLK...",
			"..KLLLLLLLLLGK..",
			".KLLLKKKKKKLGGK.",
			"KLLLKTTTTTTKGGGK",
			"KLLKTWWTTTTTKGGK",
			"KLLKTWTTTTTTKGGK",
			"KLLKTTTTTTTTKGDK",
			"KLGKTTTTTTTTKGDK",
			"KLGKTTTTTTTTKDDK",
			"KGGKTTTTTTTTKDDK",
			"KGGGKTTTTTTKDDDK",
			".KGGGKKKKKKDDDK.",
			"..KGDDDDDDDDDK..",
			"...KDDDDDDDDK...",
			"....KKKKKKKK....",
		],
	},
	{
		name: "Cascade",
		pal: { K: "#1f4a66", B: "#4fb6e3", L: "#9fdcf4", D: "#2f86b8", W: "#ffffff" },
		map: [
			".......KK.......",
			"......KBBK......",
			"......KBBK......",
			".....KBBBBK.....",
			".....KBBBBK.....",
			"....KBBBBBBK....",
			"...KBBLBBBBBK...",
			"..KBBLLBBBBBBK..",
			"..KBBLLBBBBBBK..",
			".KBBBLLBBBBBBDK.",
			".KBBBBBBBBBBBDK.",
			".KBBBBBBBBBBDDK.",
			".KBBWBBBBBBBDDK.",
			"..KBBBBBBBBDDK..",
			"...KKDDDDDDKK...",
			".....KKKKKK.....",
		],
	},
	{
		name: "Thunder",
		pal: { K: "#5a3212", Y: "#f7e27a", y: "#d9b83c", L: "#f4b36a", O: "#e0892e", o: "#b8621c", W: "#fff4d6" },
		map: [
			".......YY.......",
			"..YY..YyyY..YY..",
			"..YyYKKKKKKYyY..",
			"...YKLLLLLLKY...",
			"..YKLLOOOOOoKY..",
			"YYKLLWOOOOOooKYY",
			"YyKLOOOOOOOooKyY",
			".YKLOOOOOOOooKY.",
			".YKLOOOOOOOooKY.",
			"YyKOOOOOOOOooKyY",
			"YYKOOOOOOOoooKYY",
			"..YKOOOOOoooKY..",
			"...YKooooooKY...",
			"..YyYKKKKKKYyY..",
			"..YY..YyyY..YY..",
			".......YY.......",
		],
	},
	{
		name: "Rainbow",
		pal: {
			a: "#e8584a",
			b: "#f0a040",
			c: "#f5dc5a",
			d: "#7cc45a",
			e: "#5ac4e0",
			f: "#4a78d0",
			g: "#9a6ad0",
			h: "#e87ab8",
			N: "#2f4a9a",
			W: "#f4f1e8",
			S: "#9aa0b8",
		},
		map: [
			"......aaaa......",
			"..hh..aaaa..bb..",
			".hhhh.aaaa.bbbb.",
			".hhhhNNNNNNbbbb.",
			"..hhNNNNNNNNbb..",
			"....NNWWWWNN....",
			"ggggNWWSSWWNcccc",
			"ggggNWSWWSWNcccc",
			"ggggNWSWWSWNcccc",
			"ggggNWWSSWWNcccc",
			"....NNWWWWNN....",
			"..ffNNNNNNNNdd..",
			".ffffNNNNNNdddd.",
			".ffff.eeee.dddd.",
			"..ff..eeee..dd..",
			"......eeee......",
		],
	},
	{
		name: "Soul",
		pal: { K: "#5a1f3c", P: "#e86aa8", L: "#f4a6cc", D: "#b8487e" },
		map: [
			"................",
			"..KKKK....KKKK..",
			".KLLPPK..KPPPPK.",
			"KLLPPPPKKPPPPPDK",
			"KLPPPPPKKPPPPPDK",
			"KPPPPPPKKPPPPPDK",
			"KPPPPPPKKPPPPDDK",
			".KPPPPPKKPPPPDK.",
			".KPPPPPKKPPPPDK.",
			"..KPPPPKKPPPDK..",
			"...KPPPKKPPDK...",
			"....KPPKKPDK....",
			".....KPKKDK.....",
			"......KKKK......",
			".......KK.......",
			"................",
		],
	},
	{
		name: "Marsh",
		pal: { K: "#5a3f12", Y: "#f3c64b", L: "#fbe08a", D: "#c9972a" },
		map: [
			".....KKKKKK.....",
			"...KKYYYYYYKK...",
			"..KYLLYYYYYYDK..",
			".KYLYKKKKKKYYDK.",
			".KLYKYYYYYYKYDK.",
			"KYLKYYYYYYYYKYDK",
			"KYLKYYYYYYYYKYDK",
			"KYYKYYYYYYYYKYDK",
			"KYYKYYYYYYYYKYDK",
			"KYYKYYYYYYYYKDDK",
			"KYYKYYYYYYYYKDDK",
			".KYYKYYYYYYKYDK.",
			".KYYYKKKKKKYDDK.",
			"..KYYYYYYYYDDK..",
			"...KKDDDDDDKK...",
			".....KKKKKK.....",
		],
	},
	{
		name: "Volcano",
		pal: { K: "#3a120c", R: "#b83a26", D: "#7e2416", I: "#d8374f" },
		map: [
			"..K....KK....K..",
			"..KK..KRRK..KK..",
			"..KRK.KRRK.KRK..",
			".KRRRKRRRRKRRRK.",
			".KRRRRRRRRRRRRK.",
			"KRRRRRRKKRRRRRRK",
			"KRRRRRKIIKRRRRRK",
			"KRRRRKIIIIKRRRDK",
			"KRRRKIIIIIIKRRDK",
			"KRRRKIIIIIIKRRDK",
			"KRRRKIIIIIIKRDDK",
			".KRRRKIIIIKRRDK.",
			".KRRRRKKKKRRDDK.",
			"..KRRRRRRRRDDK..",
			"...KKDDDDDDKK...",
			".....KKKKKK.....",
		],
	},
	{
		name: "Earth",
		pal: { K: "#1f3a1c", L: "#a6d86f", G: "#62b14f", D: "#3f7f37", S: "#3a3f55" },
		map: [
			"KKKKKK..........",
			"KGGGGLKK........",
			"KGGGGLLLKK......",
			"KGGGGLLLLLK.....",
			".KGGGLLLLLLK....",
			".KGGGGLLLLLLK...",
			"..KGGGGLLLLLLK..",
			"..KDGGGGLLLLLK..",
			"...KDGGGGLLLLK..",
			"....KDDGGGLLLK..",
			".....KDDGGGLK...",
			"......KKDDDK....",
			"..........KSK...",
			"...........KSK..",
			"............KSK.",
			".............KK.",
		],
	},
	{
		name: "League",
		pal: { K: "#2b211c", R: "#d5473a", r: "#9e2f25", W: "#f4f1e8", w: "#c9c3b5" },
		map: [
			".....KKKKKK.....",
			"...KKRRRRRRKK...",
			"..KRRWRRRRRRrK..",
			".KRWRRRRRRRRRrK.",
			".KRRRRRRRRRRRrK.",
			"KRRRRRRRRRRRRRrK",
			"KRRRRRKKKKRRRrrK",
			"KKKKKKKWWKKKKKKK",
			"KWWWWWKWWKWWWWwK",
			"KWWWWWWKKWWWWwwK",
			".KWWWWWWWWWWWwK.",
			".KWWWWWWWWWWWwK.",
			"..KWWWWWWWWWwK..",
			"...KKwwwwwwKK...",
			".....KKKKKK.....",
			"................",
		],
	},
	{
		name: "Crown",
		pal: { K: "#5a3f12", Y: "#f3c64b", L: "#fbe08a", D: "#c9972a", R: "#d5473a", B: "#4a78d0" },
		map: [
			"................",
			"................",
			".K.....KK.....K.",
			"KYK...KYYK...KYK",
			"KYK...KYYK...KYK",
			"KYYK.KYYYYK.KYYK",
			"KYYYKYYYYYYKYYYK",
			"KYYYYYYLYYYYYYYK",
			"KYYYYYYYYYYYYYDK",
			"KYYYYYYYYYYYYYDK",
			"KKKKKKKKKKKKKKKK",
			"KLYRYYYBYYYRYYDK",
			"KYYYYYYYYYYYYDDK",
			"KKKKKKKKKKKKKKKK",
			"................",
			"................",
		],
	},
];

// Not-yet-won: solid dark silhouette with a slightly lighter edge (current stop
// gets a gold edge) so the shape still reads.
const silhouette = (pal, edge) => Object.fromEntries(Object.keys(pal).map((k) => [k, k === "K" ? edge : "#15131a"]));

/** state: "won" (full colour + sparkle), "here" (gold-edged silhouette), "locked". */
const GymBadge = ({ index, state = "locked", className = "" }) => {
	const badge = BADGES[index];
	if (!badge) return null;
	const pal = state === "won" ? badge.pal : silhouette({ ...badge.pal, K: "" }, state === "here" ? "#f3c64b" : "#4a4f66");
	return (
		<PixelArt map={badge.map} pal={pal} className={`gym-badge gym-badge--${state} ${className}`}>
			{state === "won" && <path className="gym-badge__spark" fill="#fff" d="M14 0h1v1h-1zM13 1h1v1h-1zM15 1h1v1h-1zM14 2h1v1h-1z" />}
		</PixelArt>
	);
};

export default GymBadge;
